### ISSUE TITLE
[bug] 区间不合理，minElement不能大于maxElement！

### ISSUE THREAD

**Issue by Xbaishu** [handyplus/monster#3]
并未从配置文件中找到对应的配置信息
当我修改后我发现出现以下报错

[12:02:22] [Server thread/INFO]: [monster] Enabling monster v3.1.0
[12:02:22] [Server thread/ERROR]: Error occurred while enabling monster v3.1.0 (Is it up to date?)
java.lang.IllegalArgumentException: 区间不合理，minElement不能大于maxElement！
	at Monster-3.1.0.jar/cn.handyplus.monster.lib.util.LotteryUtil$ContinuousList.<init>(LotteryUtil.java:67) ~[Monster-3.1.0.jar:?]
	at Monster-3.1.0.jar/cn.handyplus.monster.lib.util.LotteryUtil.<init>(LotteryUtil.java:31) ~[Monster-3.1.0.jar:?]
	at Monster-3.1.0.jar/cn.handyplus.monster.util.ConfigUtil.loadConfig(ConfigUtil.java:120) ~[Monster-3.1.0.jar:?]
	at Monster-3.1.0.jar/cn.handyplus.monster.util.ConfigUtil.getConfig(ConfigUtil.java:39) ~[Monster-3.1.0.jar:?]
	at Monster-3.1.0.jar/cn.handyplus.monster.Monster.onEnable(Monster.java:21) ~[Monster-3.1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-38-1f5db50]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-38-1f5db50]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by handy-git** [comment]
你配置概率设置的不对.可以把配置发出来看看

**Comment by Xbaishu** [comment]
> 你配置概率设置的不对.可以把配置发出来看看

已经找到问题，在附魔设置我将倍率设置为1.5
并且因为没有注明所以我没意识到数值不能超过1
